dataset_params:
  dataset: 'celeba'
  img_size: 128
  batch_size: 16
  num_workers: 4

model:
  learning_rate: 1e-4
  seed: 61
  target: 'DiT'
  condition_config:
  params:
    patch_size: 2
    hidden_size: 768
    num_layers: 12
    num_heads: 12
    out_channels: 4
  checkpoint_path: /content/drive/MyDrive/Stable-Diffusion/diffusion.pkl
  epochs: 100
  ema_decay: 0.9999

sampler:
  sampler_type: 'DDPM'
  params:
    total_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    schedule_type: 'linear'

vqmodel:
  target: model.VQModel
  params:
    embedding_dim: 4
    num_embeddings: 16384
    output_channels: 3
    channel_multipliers: [1, 2, 2, 4]
    attn_resolutions: [32]
    n_heads: 4
  checkpoint_path: /content/drive/MyDrive/Stable-Diffusion/vqmodel.pkl

wandb:
  project: 'Stable-Diffusion'
  name: 'Diffusion celebA'
