dataset_params:
  dataset: 'celeba'
  img_size: 128
  batch_size: 64
  num_workers: 4

model:
  learning_rate: 4.5e-06
  b1: 0.5
  b2: 0.9
  target: model.VQModel
  seed: 42
  params:
    embedding_dim: 4
    num_embeddings: 16384
    output_channels: 3
    commitment_cost: 0.25
    channel_multipliers: [1, 2, 2, 4]
    attn_resolutions: [32]
    n_heads: 4
  checkpoint_path: /content/drive/MyDrive/Stable-Diffusion/vqmodel.pkl
  epochs: 100
  ema_decay: 0.9999

discriminator:
  learning_rate: 4.5e-06
  b1: 0.5
  b2: 0.9
  target: discriminator.discriminator
  params:
    channel_multipliers: [1, 2, 4, 8]
    base_channels: 64
  disc_start: 5000

lpips:
  target: lpips.LPIPS

wandb:
  project: 'Stable-Diffusion'
  name: 'vq-model celebA'