dataset_params:
  dataset: 'coco'
  img_size: 128
  batch_size: 64
  num_workers: 4
  params:
    dataset_dir: /content/train2017
    ann_file_path: /content/annotations/captions_train2017.json

model:
  learning_rate: 2.0e-6
  seed: 61
  target: 'UNet'
  params:
    channel: 128
    channel_multiplier: [1, 2, 2, 4, 4]
    n_res_block: 2
    attn_strides: [2]
    attn_heads: 32
  checkpoint_path: /content/drive/MyDrive/Stable-Diffusion/coco_diffusion.pkl
  epochs: 200
  ema_decay: 0.9999

sampler:
  sampler_type: 'DDPM'
  params:
    total_timesteps: 1000
    beta_start: 0.0015
    beta_end: 0.0195
    schedule_type: 'linear'

vqmodel:
  target: model.VQModel
  params:
    embedding_dim: 4
    num_embeddings: 16384
    output_channels: 3
    channel_multipliers: [1, 2, 2, 4]
    attn_resolutions: [32]
    n_heads: 4
  checkpoint_path: /content/drive/MyDrive/Stable-Diffusion/vqmodel_coco.pkl

wandb:
  project: 'Stable-Diffusion'
  name: 'Diffusion coco'
